// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCppkNrIJcjQ_JuiBi0-433mU2i3C5fLDM',
    appId: '1:216990461675:web:1a3029ca0c211c38f618ae',
    messagingSenderId: '216990461675',
    projectId: 'proyectotest-afbd4',
    authDomain: 'proyectotest-afbd4.firebaseapp.com',
    storageBucket: 'proyectotest-afbd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQu-EvVekM3Xav6-yZx7RJBLCJ8Ms0sao',
    appId: '1:216990461675:android:33e0cdd2ceb2eedaf618ae',
    messagingSenderId: '216990461675',
    projectId: 'proyectotest-afbd4',
    storageBucket: 'proyectotest-afbd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpwcBbyZET6L1EzO5BahgQz1LXFQVsDU4',
    appId: '1:216990461675:ios:1f997e06c027061af618ae',
    messagingSenderId: '216990461675',
    projectId: 'proyectotest-afbd4',
    storageBucket: 'proyectotest-afbd4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpwcBbyZET6L1EzO5BahgQz1LXFQVsDU4',
    appId: '1:216990461675:ios:1f997e06c027061af618ae',
    messagingSenderId: '216990461675',
    projectId: 'proyectotest-afbd4',
    storageBucket: 'proyectotest-afbd4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCppkNrIJcjQ_JuiBi0-433mU2i3C5fLDM',
    appId: '1:216990461675:web:1349dffa18f1c7a8f618ae',
    messagingSenderId: '216990461675',
    projectId: 'proyectotest-afbd4',
    authDomain: 'proyectotest-afbd4.firebaseapp.com',
    storageBucket: 'proyectotest-afbd4.firebasestorage.app',
  );
}